### ISSUE TITLE
Unable to tokenize in case of <ins class=...

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#795]
When I was running the yoastseo-node module , I encountered the following error: 
### Error in console

```
Trace: { [Error: unable to tokenize]
  tokenizer2: 
   { buffer: '<ins class="adsbygoogle responsive-tarnfarbe-nach-more"',
     line: 1,
     col: 1 } }
    at showTrace (/Users/Irene/Documents/yoastseo-node/node_modules/yoastseo/js/helpers/errors.js:17:11)
    at Assessor.executeAssessment (/Users/Irene/Documents/yoastseo-node/node_modules/yoastseo/js/assessor.js:174:3)
    at arrayMap (/Users/Irene/Documents/yoastseo-node/node_modules/lodash/_arrayMap.js:16:21)
    at map (/Users/Irene/Documents/yoastseo-node/node_modules/lodash/map.js:51:10)
    at Assessor.assess (/Users/Irene/Documents/yoastseo-node/node_modules/yoastseo/js/assessor.js:130:17)
    at Analyze (/Users/Irene/Documents/yoastseo-node/analyse.js:34:29)
    at Query._callback (/Users/Irene/Documents/yoastseo-node/analyse.js:82:9)
    at Query.Sequence.end (/Users/Irene/Documents/yoastseo-node/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
    at Query._handleFinalResultPacket (/Users/Irene/Documents/yoastseo-node/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/Users/Irene/Documents/yoastseo-node/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
```
## Input

```
  <p><img src="http://karrierebibel.de/wp-content/uploads/2014/12/Interkulturelle-Kompetenzen-International-Test.jpg" alt="Interkulturelle-Kompetenzen-International-Test" width="650" /><br />
Die Welt wächst zusammen. Dabei ist auch die <strong>Arbeitswelt internationaler</strong> geworden. Viele deutsche Unternehmen haben Standorte im Ausland, unterhalten Geschäftsbeziehungen zu Partnern auf allen Kontinenten und auch in heimischen Teams arbeiten Menschen aus den unterschiedlichsten Ländern und Kulturen. Wenn aber Menschen mit unterschiedlichen Hintergründen aufeinander treffen, sind auch Fettnäpfchen nicht weit. Etwas <strong>interkulturelle Kompetenz</strong> erleichtert daher das Verständnis für andere Kulturen und hilft, eben diese Fettnäpfchen zu umgehen. Und das lässt sich lernen und trainieren. Zum Beispiel jetzt... <div class="adslot-widget"><center class="google_ads"><a class="link" href="http://karrierebibel.de/mediadaten"></a><style>
.responsive-tarnfarbe-nach-more { width: 300px; height: 250px; }
@media(min-width: 500px) { .responsive-tarnfarbe-nach-more { width: 500px; height: 300px; } }
@media(min-width: 800px) { .responsive-tarnfarbe-nach-more { width: 650px; height: 300px; } }
</style>
<script defer src="http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- RESPONSIVE Tarnfarbe nach MORE -->
<ins class="adsbygoogle responsive-tarnfarbe-nach-more"
     style="display:inline-block"
     data-ad-client="ca-pub-7285045913003127"
     data-ad-slot="8948646431"
     data-ad-region="REGION_1"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></center></div></p>
<h3>Andere Länder, andere Sitten</h3>
<p>Diese Redewendung kennen Sie sicherlich. In Deutschland reicht man sich zur Begrüßung die Hand, in den meisten asiatischen Ländern nicht. Hierzulande ist Pünktlichkeit eine Tugend und wird erwartet, doch beispielsweise in Frankreich ist man bei einer Viertelstunde Verspätung immer noch pünktlich. Doch wer sich dieser <strong>Unterschiede</strong> nicht bewusst ist, ist schnell frustriert und läuft zusätzlich Gefahr, sich in den Augen des anderen unangebracht zu verhalten. Eine gute Zusammenarbeit ist dann nicht mehr möglich. Als Folge scheitern Geschäftsreisen und Entsendungen von Mitarbeitern an ausländische Standorte und internationale Teams werden handlungsunfähig. Das Ergebnis: Frust auf beiden Seiten. </p>
<p>Dahinter steht folgendes <strong>Problem</strong>: Der kulturelle Hintergrund des jeweils anderen wird nicht berücksichtigt. Sein Verhalten, seine Arbeitsweise, seine Art zu Verhandeln werden aus der eigenen Perspektive heraus betrachtet und beurteilt. Ein Denken in den Kategorien "besser" oder "schlechter" ist die Folge. Nicht selten landet man dann bei Beurteilungen à la "Die Franzosen sind unpünktlich" oder "Die Amerikaner sind oberflächlich". </p>
<p>Wird jedoch die <strong>kulturelle Prägung</strong> berücksichtigt, ändern sich diese Bilder wieder. Die bloße Beurteilung weicht dem Verständnis. Der eigene Blickwinkel wird erweitert. Das sorgt für bessere Ergebnisse. Studien zeigen, dass internationale Teams, deren Teilnehmer hohes Verständnis für die unterschiedlichen Kulturen ihrer Teammitglieder mitbringen, kreativer und lösungsorientierter arbeiten als Teams mit dem selben kulturellen Hintergrund. </p>
<div class="textboxright1" style="width:94%">
<h3>Definition interkulturelle Kompetenz: Was ist das eigentlich?</h3>
<p>Wie entwickelt man sein Verständnis für andere Kulturen? Im Fachjargon nennt sich diese Fähigkeit interkulturelle Kompetenz. Wer sich diese Fähigkeit aneignen will, braucht: </p>
<ol>
<li>
<h4>Offenheit</h4>
<p> Sie werden mit noch unbekannten und fremdartigen Verhaltensweisen konfrontiert. Nur wer Interesse zeigt und offen für Neues ist, kann unvoreingenommen damit umgehen. Offenheit ermöglicht es Ihnen, sich auf das neue Umfeld einzulassen und dazuzulernen.</li>
<li>
<h4>Bereitschaft zur Reflexion</h4>
<p> Die Auseinandersetzung mit der fremden, aber auch der eigenen Kultur ist notwendig. Sie sollten bereit sein auch Ihr eigenes Verhalten und Ihren kulturellen Hintergrund unter die Lupe zu nehmen. Wie wirkt das, was ich sage und tue auf andere? Sind Ihnen die Unterschiede bewusst, fällt es Ihnen leichter darauf einzugehen.</li>
</ol>
<p>Ziel ist es <strong>Handlungssicherheit</strong> zu gewinnen und souverän mit Menschen aus anderen Kulturen umgehen zu können. Sie werden das Verhalten Ihres Gegenübers besser einschätzen können und richten Ihre Verhalten und Ihre Kommunikation danach aus. </p>
<h3>Quiz: Sind Sie fit fürs internationale Parkett?</h3>
<p>Wie viel wissen Sie über andere Kulturen? Wären Sie bereit für ein Treffen mit japanischen Geschäftspartnern? Testen Sie mit unserem <a href="http://karrierebibel.de/quiz-wie-sicher-sind-sie-auf-internationalem-parkett/" target="_blank"><strong>Quiz</strong></a> Ihr Wissen.
</div>
<h2>Interkulturelle Kompetenz: Ein Auslandsknigge</h2>
<p>Um ein Verständnis entwickeln zu können, braucht es das Wissen um die Sitten, Werte und Traditionen verschiedener Länder. Deswegen finden Sie hier einige <strong>nützliche Informationen zu den Gepflogenheiten einiger Länder</strong>: </p>
<ul>
<li>
<h2>Interkulturelle Kompetenz: China</h2>
<ul>
<li>
<h4>Begrüßung</h4>
<p> <img src="http://karrierebibel.de/wp-content/uploads/2014/12/Internationale-Kompetenz_china.jpg" alt="Interkulturelle Kompetenz: China" width="300" class="alignright" />Umarmungen und enger Körperkontakt sind hier tabu. Der Handschlag nicht allzu verbreitet, allenfalls wenn Ihr Gegenüber sich schon auf Europäer eingestellt hat, wird er Ihnen die Hand reichen. Ansonsten ist die leichte Verbeugung üblich. Hierbei gilt: Neigen Sie sich möglichst ähnlich tief, wie Ihr Gegenüber. Beugen Sie sich tiefer, stellen Sie sich im Rang unter ihn, ist es deutlich höher, werten Sie Ihr Gegenüber ab. Das gilt in abgeschwächter Form auch für das Kopfnicken - also die Andeutung einer Verbeugung. Ganz wichtig aber: Immer lächeln dabei. Und: Begrüßen Sie stets den Ranghöchsten zuerst!</li>
<li>
<h4>Kleidung</h4>
<p> Erscheinen Sie im Zweifel lieber overdressed. Für seinen Geschäftspartner in edle Markenkleidung zu schlüpfen, drückt Wertschätzung aus und wird durchaus registriert. Manche Chinesen lassen deshalb auch gerne mal das Markenschild an ihrem Anzug hängen - was hierzulande eher als schwerer Fauxpas gilt. Dunkle Farben sind aber ein Muss - Weiß zum Beispiel wird auf Beerdigungen getragen.</li>
<li>
<h4>Geschäftsessen</h4>
<p> Essen dient in China eher der Nahrungsaufnahme und wird weniger zelebriert. Die einzelnen Gänge werden deshalb oft zusammen serviert, zügig verputzt und auch wieder abgeräumt. Lautes Schlürfen gilt als Zeichen, dass es Ihnen schmeckt. Vorsicht indes beim Reis: Stäbchen nie in den Reis stecken, das symbolisiert den Tod. Und falls Sie eingeladen haben: Wundern Sie sich nicht, dass Ihr Gegenüber nur zurückhaltend isst. Chinesen möchten mehrfach aufgefordert werden, kräftig zuzulangen. Das gilt als höflich. Der eigentliche Smalltalk und die Verhandlungen werden erst nach dem Essen, vorzugsweise an der Bar begonnen.</li>
<li>
<h4>Smalltalk</h4>
<p> Privates gehört hier zum Plaudern unbedingt dazu. Chinesen werden sich deshalb gerne nach Ihrer Familie oder den Kindern erkundigen. Wer eine große Familie und viele Söhne hat, sammelt hier durchaus Pluspunkte. Auch Fragen nach dem Gehalt sind nicht unüblich. Ebenso wird sich gerne nach dem Hotel erkundigt, in dem Sie wohnen. Achtung: Wählen Sie daher ruhig ein besseres Hotel - das wertet Sie sofort auf.</li>
<li>
<h4>Körpersprache</h4>
<p> Chinesen mögen weder hektische noch ausladende Bewegungen. Wenn Sie etwas erklären oder durch Ihre Körpersprache unterstreichen möchten, machen Sie daher möglichst ruhige Gesten und lassen Sie die Arme nah am Körper. Ebenso wichtig: leise sprechen. Flüstern sollten Sie freilich auch nicht, aber wer laut wird, verliert sein Gesicht.</li>
<li>
<h4>Blumen</h4>
<p> Egal, ob Sie privat eingeladen sind oder jemanden zum Geschäftsessen treffen: Bringen Sie bloß keine Blumen mit, das gilt im Land der aufgehenden Sonne als Unglücksbote und daher als Beleidigung. Mit Pralinen oder anderen Süßigkeiten machen Sie indes nichts verkehrt. Am besten handelt es sich dabei noch um edle Markenware. Allerdings: Achten Sie darauf, dass nichts, was Sie verschenken in irgendeiner Weise mit der Unglückszahl Vier zu tun hat. Acht dagegen ist die Glückszahl.</li>
</ul>
</li>
<li>
<h2>Interkulturelle Kompetenz: Frankreich</h2>
<ul>
<li>
<h4>Pünktlichkeit</h4>
<p> <img src="http://karrierebibel.de/wp-content/uploads/2014/12/Internationale-Kompetenz_Frankreich-1.jpg" alt="Interkulturelle Kompetenz: Frankreich" width="300" class="alignright" />Für die deutsche Primärtugend gibt es bei unserem Nachbarn eine sehr dehnbare Auslegung: <a href="http://karrierebibel.de/puenktlichkeit-unpuenktlichkeit/" target="_blank">Pünktlich</a> ist man auch noch, wenn man sich um bis zu 15 Minuten verspätet. Was in Paris aber auch gerne mit der Metro entschuldigt wird.</li>
<li>
<h4>Geschäftsessen</h4>
<p> Franzosen regeln geschäftliche Dinge gerne beim Essen. Korrekter wäre allerdings: nach dem Essen. Denn erst nach dem Dessert wird über den Job gesprochen - die Zeit davor dient ausschließlich dem Smalltalk. Bevor Sie sich irgendwo hinsetzen: Warten Sie auf jeden Fall, bis der Kellner Ihnen einen Platz zuweist. Den können Sie auch ablehnen, nur selber aussuchen wäre grob unhöflich. Eine Einladung zum Essen abzulehnen übrigens auch. Wenn Sie wenig Zeit haben, wechseln Sie lieber ins Bistro. Lautes Anstoßen oder sich Zuprosten gilt hier als unfein, das Glas wird lediglich erhoben. Dabei sieht man jeden einmal kurz an. Ebenso verpönt sind in Frankreich getrennte Rechnungen. Wer einlädt, zahlt auch für alle.</li>
<li>
<h4>Kleidung</h4>
<p> Die darf in Frankreich schon mal etwas legerer sein, aber nicht zu leger. Die Krawatte ist nicht immer zwingend erforderlich, der Anzug oder eine Kombination indes schon. Jeans geht nicht.</li>
<li>
<h4>Smalltalk</h4>
<p> Der Deutsche prahlt schon mal ganz gerne mit seinen Leistungen und Errungenschaften. Fatal! Franzosen empfinden es als tugendhafter, auch mal über die eigenen Fehler zu sprechen. Auch sollte man nie offen widersprechen - unfein. Das haben die Franzosen mit den Asiaten gemein: Man wahrt stets das Gesicht des anderen und redet lieber um den heißen Brei.</li>
</ul>
</li>
<li>
<h2>Interkulturelle Kompetenz: USA</h2>
<ul>
<li>
<h4>Termine</h4>
<p> <img src="http://karrierebibel.de/wp-content/uploads/2014/12/Internationale-Kompetenz_Frankreich-2.jpg" alt="Interkulturelle Kompetenz: USA" width="300" class="alignright" />Amerikaner erwarten von Deutschen Pünktlichkeit, halten sich aber selbst nicht unbedingt daran. Als grob unhöflich indes gilt, zu früh zu erscheinen, vor allem bei Abendveranstaltungen. Überhaupt: Wenn Sie sich geschäftlich mit Amerikanern treffen wollen, sollten Sie das nicht abends machen. Zwar wird in den USA oft abends länger gearbeitet - danach aber zieht es die Amerikaner nach Hause zur Familie. Wenn sich der Abendtermin also partout nicht vermeiden lässt, laden Sie lieber zu einem informellen Treffen mit der Familie ein - ein Barbecue zum Beispiel. Die generelle Attitüde, die Sie sich in den USA unbedingt aneignen sollten, strahlt Freundlichkeit, Selbstbewusstsein und Optimismus aus.</li>
<li>
<h4>Begrüßen</h4>
<p> Auf das obligatorische angelsächsische "How are you" antworten Sie bitte niemals ehrlich, sondern stets positiv, also "I'm fine, thank you". Überhaupt darf in den USA alles ein bisschen größer und überschwänglicher sein. Komplimente etwa. Wenn Sie etwas loben - das Büro, den Blick aus dem Meetingraum, die Stadt -, dann ist das mindestens "great", besser noch "awesome". Tabu dagegen: Jede Form von Kritik oder Gejammer sowie Komplimente zum Aussehen. Insbesondere gegenüber Personen des anderen Geschlechts könnte das als sexuelle Belästigung ausgelegt werden. Ihr Händedruck ist dagegen kurz und kräftig.</li>
<li>
<h4>Geschäftsessen</h4>
<p> In den USA gelten andere Tischmanieren als bei uns. Fleisch oder Fisch wird dort in der Regel erst in mundgerechte Happen geschnitten und dann mit der Gabel und der rechten Hand gegessen. Die Linke bleibt dabei unter dem Tisch im Schoß liegen. Als Europäer dürfen Sie aber ihre gewohnten Tischsitten beibehalten, das wird akzeptiert - auch wenn anpassen freilich netter wäre.</li>
<li>
<h4>Alkohol</h4>
<p> Ist im Business verpönt. Zum Mittagessen sowieso tabu - es sei denn, Sie sind Charly Sheen. Trinken Sie lieber Wasser oder Softdrinks wie Eistee oder Cola.</li>
<li>
<h4>Smalltalk</h4>
<p> Tabu ist alles, was schwierig werden könnte: Religion, Rasse, Sex, Politik. Vor allem Politik! Unterstehen Sie sich, den Präsidenten zu kritisieren! Das dürfen nur Amerikaner, aber keine Ausländer. Dafür lieben Amerikaner ihr Land zu sehr. Nörgeln Sie umgekehrt aber auch nicht an den hiesigen Politikern rum - unfein. Viel wichtiger ist dafür, sich möglichst oft und für alles zu bedanken und Leute miteinander bekannt zu machen und positive Leistungen oder Erfolge lobend zu erwähnen. Ob Sie mit Ihrer Charmeoffensive erfolgreich waren, können Sie hinterher an der Visitenkarte ablesen: Die verteilen Sie nämlich nicht einfach, sondern fragen lieber zuerst nach der Ihres Gegenübers. Sind die ihm leider "ausgegangen", hat er kein weiteres Interesse.</li>
<li>
<h4>Trinkgeld</h4>
<p> Mit dem sogenannten <a href="http://karrierebibel.de/trinkgeld-tabelle-tipps/" target="_blank">Tip</a> sollten Sie in den USA großzügig sein. In Europa ist es zum Beispiel so: Je weiter man in den Süden kommt, desto mehr Trinkgeld wird erwartet. In den USA aber liegen die Gehälter in vielen Dienstleistungsberufen so niedrig, dass die Angestellten auf Trinkgeld angewiesen sind. Der Hotelpage, der Ihnen etwa das Gepäck aufs Zimmer bringt, erwartet bis zu zwei Dollar pro Gepäckstück. Und die Kellnerin bis zu 20 Prozent des Rechnungsbetrages.</li>
</ul>
</li>
<li>
<h2>Interkulturelle Kompetenz: Japan</h2>
<ul>
<li>
<h4>Begrüßen</h4>
<p> <img src="http://karrierebibel.de/wp-content/uploads/2014/12/Internationale-Kompetenz_Japan.jpg" alt="Interkulturelle Kompetenz: Japan" width="300" class="alignright" />Anders als Südeuropäer wahren Japaner beim ersten Kennenlernen körperliche Distanz. Umarmen, Schulterklopfen, Händeschütteln, überhaupt Berührungen aller Art sind hier verpönt. Eine Verbeugung oder ein Nicken reichen. Und beides sollte - wie in China - so tief ausfallen wie bei Ihrem Gegenüber.</li>
<li>
<h4>Hierarchie</h4>
<p> Ist in Japan unbedingt zu beachten. Wer einen hohen Rang hat, erwartet, dass Sie das bemerken und respektieren. Was bedeutet, dass Sie dieser Person die größte Aufmerksamkeit und Ehre bekunden. Tipp: Die Visitenkarte kann Ihnen hierzu erste wertvolle Hinweise geben. Je weniger draufsteht, desto wichtiger Ihr Gegenüber. Steht dort gar nur sein Name, erwartet er, dass Sie wissen, wer er ist.</li>
<li>
<h4>Visitenkarten</h4>
<p> Eine <a href="http://karrierebibel.de/visitenkarte-erstellen-design-tipps/" target="_blank">Visitenkarte</a> zu überreichen, kommt in Japan einem Ritual gleich. Nie sollten Sie diese aus der Hosentasche zücken. Allein angebracht ist, diese aus der Jackentasche und einem edlen Etui zu nehmen sowie sie anschließend mit beiden Händen zu überreichen. Zu dem Ritual gehört dann allerdings auch, die Karte nicht sofort wegzustecken, sondern sich noch ein wenig über das Aufgedruckte oder manche Schriftzeichen zu unterhalten. Respektsbekundung! Überreichen Sie überdies noch ein Geschenk, sollten Sie dies mit der Formel "Es ist zwar wertlos, aber nehmen Sie es bitte trotzdem an" tun. Klar, das Ihr Präsent sehr wohl wertvoll ist! Und wundern Sie sich nicht, wenn Ihr Gegenüber das Mitbringsel vorerst ungeöffnet zur Seite legt - er will nur nicht habgierig wirken.</li>
<li>
<h4>Geschäftsessen</h4>
<p> Auch hierbei wird stark auf die Hierarchie geachtet. Je höher der Rang, desto weiter von der Tür weg werden Sie oder Ihr Gast platziert. Falls Sie in einem traditionellen Restaurant auf Tatami-Matten Platz nehmen, fläzen Sie sich bitte nicht, sondern nehmen Sie den Schneidersitz ein. Ganz wichtig: Weil Sie dazu die Schuhe ausziehen müssen, sollten Sie unbedingt auf edle und lochfreie Socken achten. Fußgeruch ist ein schwerer Fauxpas. Ebenso sollten Sie sich beim Trinken niemals zuerst nachschenken. Gießen Sie dem anderen zuerst etwas ein - Sakeschalen sind aber vorher zu leeren. Und falls Sie die Rechnung bezahlen wollen, müssen Sie das unauffällig dem Kellner sagen. Ansonsten wird die Rechnung automatisch an den Japaner gehen - und der wird sie wortlos bezahlen. Eine Rechnung zu prüfen gilt als unfein.</li>
<li>
<h4>Kleidung</h4>
<p> In Asien legt man generell großen Wert auf Qualität, teures Tuch, angesagte Marken und dezente Noblesse. Ein legeres Outfit wird gern mit Nichtachtung gleichgesetzt. Nichts verkehrt machen Sie mit einem dunklem und teuren Anzug oder Kostüm. Achten Sie aber unbedingt auch auf Socken, Schuhe und deren Innenleben - zumal Schuhe auf Tatamimatten gerne ausgezogen werden und jeder dann einen Blick darauf wirft. Aber auch beim Reisegepäck können Sie sich verraten. Egal, ob Trolley oder Reisetasche - achten Sie auf erkennbare Markenware.</li>
<li>
<h4>Komplimente</h4>
<p> Japaner lieben und brauchen Harmonie. Deswegen werden hier Konflikte auch nie offen ausgetragen, sondern allenfalls indirekt. Auch Gefühle, wie etwa Unbehagen oder Enttäuschung, werden nicht offen angesprochen. Umgekehrt sollten Sie auch keine direkten Komplimente machen. Das wirkt auf Japaner wie eine Ausrede - und damit Kritik. Betonen Sie lieber eigene Schwächen, um Ihr Gegenüber aufzuwerten - oder fragen Sie um Rat. Höchste Anerkennung.</li>
</ul>
</li>
<li>
<h2>Interkulturelle Kompetenz: Arabische Länder</h2>
<ul>
<li>
<h4>Anrede</h4>
<p> <img src="http://karrierebibel.de/wp-content/uploads/2014/12/Internationale-Kompetenz_Saudi-Arabien.jpg" alt="Interkulturelle Kompetenz: Arabische Länder" width="300" class="alignright" />Formell mit Titel und Nachnamen; gesellschaftlicher Status und berufliche Position sind zentral. Die in den Golfstaaten übliche Anrede mit Vornamen (Mr. Hans, Mr. Ahmed) entspricht nicht unserem Duzen. Die informelle, aber respektvolle Anrede setzt sich aus der Bezeichnung Abu (Vater von) oder Umm (Mutter) und dem Namen des erstgeborenen Sohnes (inzwischen auch Tochter) zusammen (Abu Muhammad). Im Schriftverkehr: der volle Name mit Titel.</li>
<li>
<h4>Begrüßung</h4>
<p> Das richtige Verhalten Männern gegenüber: Mit <em>as-salamu alaykum</em>("Friede sei mit Dir") und der Antwort – <em>wa-alaykum as-salam</em> ("Auch mit Dir sei Friede") – liegen Sie immer richtig. Auf den Gruß folgt die Frage nach dem Befinden. Die Antwort: <em>bi-khayr</em> ("gut") oder <em>al-hamdu-lillah</em> ("Lob sei Gott!"). Wer einen Raum mit mehreren Personen betritt, begrüßt erst den Gastgeber, dann den Ältesten, schließlich alle anderen. Dazu gehört ein sanfter (!) Händedruck.<br />
<br />
Das richtige Verhalten Frauen gegenüber: Vermeiden Sie Körperkontakt! Arabische Frauen werden – je nach Umfeld – höchst zurückhaltend begrüßt. Warten Sie ab, ob die Dame Ihnen die Hand reicht. Falls nicht, genügt kurzes Kopfnicken. Werden Sie als Frau von arabischen Männern nicht gegrüßt oder gar nicht ins Gespräch einbezogen, ist das kein Affront, sondern Beweis ihrer Ehrerbietung. Als Geschäftspartnerin nimmt man Sie jedoch in Ihrer Rolle ernst, solange Sie nicht zu persönlich werden.</li>
<li>
<h4>Kleidung</h4>
<p> Nachlässige Kleidung bedeutet hier Mangel an Wohlstand und Bildung. Ungeachtet der Temperatur sind Anzug und Krawatte Pflicht, kurze Hosen und Ärmel nur beim Sport erlaubt. Frauen tragen Hosenanzug oder ein Knie bedeckendes Kostüm mit Strümpfen. Bloße Schultern und Oberarme, tiefe Dekolletés oder Beinschlitze sind tabu. In Saudi-Arabien müssen auch nichtarabische Frauen die <em>abaya</em>, das traditionelle schwarze Gewand, tragen.</li>
<li>
<h4>Geschäftsessen</h4>
<p> Traditionellerweise ersetzen Brotstücke das Besteck. Brot stets mitessen und kein zweites Mal in die Speisen tauchen! Die linke Hand gilt im islamischen Raum als unrein und sollte nicht zum Essen benutzt werden. In konservativen Familien essen Männer und Frauen getrennt. Als Gast wird man stets aufgefordert, mehr zu essen. Sich zu zieren, gehört zum guten Ton. Wenn Sie nicht mehr können, lassen Sie einen Rest auf dem Teller und lehnen Sie dreimal freundlich ab. Nach dem Kaffee ist es Zeit, zu gehen. Das Auffordern zum Bleiben ist nur Teil des Rituals. Eine Gegeneinladung wird erwartet. Die Gastfreundschaft ist Prüfstein der arabischen Geschäftskultur: Zu jedem Treffen werden Getränke gereicht – Wasser, Tee, Kaffee, Fruchtsäfte. Bieten Sie arabischen Gästen die Erfrischungen mehrmals an, sonst werden sie nichts zu sich nehmen.</li>
<li>
<h4>Verhandeln</h4>
<p> Sagen, was Sache ist, gilt als ungebildet. Faustregel: Sagt ein diplomatischer Araber "ja", meint er "vielleicht", sagt er "vielleicht", meint er "nein". Hinterfragen Sie Aussagen wie "No problem!" Und das Wichtigste wird immer am Schluss angesprochen. Feilschen gehört hier zur Kultur. Planen Sie stets Zeit und Verhandlungsspielraum ein, besonders bei Preisen. Emotionale Ausbrüche aber auch Schweigen gehören zur Show. Auch wenn im Ehrenkodex gilt "Ein Mann – ein Wort", sollten Vereinbarungen schriftlich fixiert werden. Notfalls verweisen Sie auf formal-organisatorische Gründe.</li>
<li>
<h4>Visitenkarten</h4>
<p> Werden mit der rechten Hand überreicht und entgegengenommen, meist nach der Begrüßung. Dank und Respekt für die Karte des Gegenübers sind selbstverständlich. Bitte nichts darauf notieren!</li>
</ul>
</li>
</ul>
```

**Comment by moorscode** [comment]
No longer happens in 9.2
